### ISSUE TITLE
How to read all unread msgs from all chats

### ISSUE THREAD

**Issue by xmrxmr00** [danielcardeenas/sulla#111]
Hi All,
Good project, well done!
How to read all unread msgs from all chats?

**Comment by rfscheidt** [comment]
I have the same issue, the getAllChats method don't retrieve messages.

**Comment by vasani-arpit** [comment]
There is a getUnreadMessages method  https://github.com/danielcardeenas/sulla/blob/master/src/lib/wapi.js#L817 in a lib but I am not sure there is TS wrapper around it or not.

**Comment by smashah** [comment]
Please try this and let me know if it works for you thanks

https://github.com/smashah/sulla/commit/484dbc4ceb1b8754573697139d02e48087ee704f

**Comment by rfscheidt** [comment]
Yes, now it's bringing the message. But if I reload the screen, it no longer brings, I need to run the server again (and delete the session). I think this is not right, because on the cell phone remains unread, it should always bring, until the phone marks read. Not?

**Comment by rfscheidt** [comment]
yes, it's work!!! Thanks you very much!

**Comment by rfscheidt** [comment]
Is there any way I can read the messages already read again?

**Comment by vasani-arpit** [comment]
Yes. you can there is a ```getAllMessagesInChat``` in wapi.js which you can utilize for that purpose.

**Comment by rfscheidt** [comment]
How do I use wapi.js method that is not mapped in whatsapp.d.ts?

**Comment by smashah** [comment]
@rfscheidt request it via a new issue in the relevant repo or implement and do a PR.

**Comment by smashah** [comment]
getAllMessagesInChat  is implemented in 446da9a

**Comment by rfscheidt** [comment]
Time:  1574692056782
(node:46721) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'participants' of undefined
    at Object.window.WAPI._getGroupParticipants (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/sulla-hotfix/dist/lib/wapi.js:548:21)
    at async Object.window.WAPI.getGroupParticipantIDs (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/sulla-hotfix/dist/lib/wapi.js:559:21)
    at ExecutionContext._evaluateInternal (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by smashah** [comment]
@rfscheidt 
Do not use ```_getGroupParticipants```, it does not work. Please use the right repo for talking about issues. This is for original sulla, not hotfix.
