### ISSUE TITLE
Cannot run on heroku

### ISSUE THREAD

**Issue by comcloudway** [danielcardeenas/sulla#211]
Heroku cannot start chrome instance.

Log:
2020-03-17T07:46:58.241549+00:00 app[web.1]: > node app.js
2020-03-17T07:46:58.241549+00:00 app[web.1]: 
2020-03-17T07:46:58.541815+00:00 app[web.1]: - Initializing whatsapp
2020-03-17T07:46:58.560718+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
2020-03-17T07:46:58.560724+00:00 app[web.1]: /app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
2020-03-17T07:46:58.560727+00:00 app[web.1]: 
2020-03-17T07:46:58.560727+00:00 app[web.1]: 
2020-03-17T07:46:58.560728+00:00 app[web.1]: TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
2020-03-17T07:46:58.560728+00:00 app[web.1]: 
2020-03-17T07:46:58.560735+00:00 app[web.1]: at onClose (/app/node_modules/puppeteer/lib/Launcher.js:750:14)
2020-03-17T07:46:58.560735+00:00 app[web.1]: at Interface.<anonymous> (/app/node_modules/puppeteer/lib/Launcher.js:739:50)
2020-03-17T07:46:58.560738+00:00 app[web.1]: at Interface.emit (events.js:323:22)
2020-03-17T07:46:58.560738+00:00 app[web.1]: at Interface.close (readline.js:409:8)
2020-03-17T07:46:58.560739+00:00 app[web.1]: at Socket.onend (readline.js:187:10)
2020-03-17T07:46:58.560739+00:00 app[web.1]: at Socket.emit (events.js:323:22)
2020-03-17T07:46:58.560742+00:00 app[web.1]: at endReadableNT (_stream_readable.js:1204:12)
2020-03-17T07:46:58.560742+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-03-17T07:46:58.560804+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2020-03-17T07:46:58.560892+00:00 app[web.1]: (node:23) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020-03-17T07:46:58.642343+00:00 heroku[web.1]: Process exited with status 0

**Comment by comcloudway** [comment]
I've installed this buildpack https://elements.heroku.com/buildpacks/jontewks/puppeteer-heroku-buildpack
in addition to my nodejs one and now it seems to be working.
