### ISSUE TITLE
Initializing whatsapp(node:11037) UnhandledPromiseRejectionWarning: Error

### ISSUE THREAD

**Issue by Michaelsafir** [danielcardeenas/sulla#229]
Hello, i need to deploy sulla on my server, but i have error, i think - on server no such app as chrome. What can i do to run code on server? 

traceback: 

Initializing whatsapp(node:11037) UnhandledPromiseRejectionWarning: Error
    at new LauncherError (/home/re/bot2/node_modules/chrome-launcher/dist/utils.js:35:22)
    at new ChromePathNotSetError (/home/re/bot2/node_modules/chrome-launcher/dist/utils.js:42:9)
    at Object.linux (/home/re/bot2/node_modules/chrome-launcher/dist/chrome-finder.js:108:15)
    at Function.getInstallations (/home/re/bot2/node_modules/chrome-launcher/dist/chrome-launcher.js:126:51)
    at /home/re/bot2/node_modules/sulla/dist/controllers/browser.js:116:66
    at step (/home/re/bot2/node_modules/sulla/dist/controllers/browser.js:44:23)
    at Object.next (/home/re/bot2/node_modules/sulla/dist/controllers/browser.js:25:53)
    at /home/re/bot2/node_modules/sulla/dist/controllers/browser.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/home/re/bot2/node_modules/sulla/dist/controllers/browser.js:15:12)

**Comment by danielcardeenas** [comment]
On it

**Comment by danielcardeenas** [comment]
Fixed here: https://github.com/danielcardeenas/sulla/commit/6baa1cd9d494105391d37804e8a63dff53527bb3
Please update to version `sulla@2.3.2`.
Also, note that if you cant have installed **Chromium** or **chrome**, sulla will not work
