### ISSUE TITLE
Retrieve all messages in chat

### ISSUE THREAD

**Issue by AlexanderPineda** [danielcardeenas/sulla#265]
How can I use the method: 
const allMessages = await client.loadAndGetAllMessagesInChat(chatId);,

I was trying a lot of times but i think it doesn't work, please explainme how can I obtain all messages from a conversation

Thanks

**Comment by robertsLando** [comment]
Please provide the chatid you are using (it must end with “@c.us”) and also try to start sulla with headless false and devTools true to see if there are errors in developer console of the windows that opens

---

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by AlexanderPineda** [comment]
@robertsLando hi my friend, I followed your instructions but it's keeping showing tha same issue, I can´t use the client.loadAndGetAllMessagesInChat function.

this is the error message showed in console
(node:7160) UnhandledPromiseRejectionWarning: ReferenceError: client is not defined
    at mostrarChats (C:\Users\LENOVO\Desktop\whatsapptest2\app.js:32:25)
    at C:\Users\LENOVO\Desktop\whatsapptest2\app.js:16:13
    at C:\Users\LENOVO\Desktop\whatsapptest2\node_modules\sulla\dist\api\layers\listener.layer.js:67:20
    at Page._onBindingCalled (C:\Users\LENOVO\Desktop\whatsapptest2\node_modules\puppeteer\lib\Page.js:558:56)
    at CDPSession.<anonymous> (C:\Users\LENOVO\Desktop\whatsapptest2\node_modules\puppeteer\lib\Page.js:119:54)
    at CDPSession.emit (events.js:223:5)
    at CDPSession._onMessage (C:\Users\LENOVO\Desktop\whatsapptest2\node_modules\puppeteer\lib\Connection.js:200:12)
    at Connection._onMessage (C:\Users\LENOVO\Desktop\whatsapptest2\node_modules\puppeteer\lib\Connection.js:112:17)
    at WebSocket.<anonymous> (C:\Users\LENOVO\Desktop\whatsapptest2\node_modules\puppeteer\lib\WebSocketTransport.js:44:24)
    at WebSocket.onMessage (C:\Users\LENOVO\Desktop\whatsapptest2\node_modules\ws\lib\event-target.js:120:16)
(node:7160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by AlexanderPineda** [comment]
Hi everyone, the mistake was mine, I was using from a bad way the method thaks a lot for your support. the method is work good, an advice would be show more documentation and examples of use about  the Retrieving data Functions. thankss
