### ISSUE TITLE
addParticipant not working

### ISSUE THREAD

**Issue by roysG** [danielcardeenas/sulla#270]
(node:66773) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: n is not a function
    at /Users/roysabah/www/msgto/server/node_modules/sulla/dist/lib/wapi/wapi.js:1:28035
    at q (https://web.whatsapp.com/app.ca7f73985b45fbf63033.js:1:23752)
    at MutationObserver.V (https://web.whatsapp.com/app.ca7f73985b45fbf63033.js:1:23258)

**Comment by danielcardeenas** [comment]
Can you please show me the error

**Comment by roysG** [comment]
(node:72769) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: n is not a function
    at /Users/roysabah/www/xx/server/node_modules/sulla/dist/lib/wapi/wapi.js:1:28035
    at q (https://web.whatsapp.com/app.ca7f73985b45fbf63033.js:1:23752)
    at MutationObserver.V (https://web.whatsapp.com/app.ca7f73985b45fbf63033.js:1:23258)
    at ExecutionContext._evaluateInternal (/Users/roysabah/www/xx/server/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/roysabah/www/xx/server/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/Users/roysabah/www/xx/server/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/Users/roysabah/www/xx/server/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/Users/roysabah/www/xx/server/node_modules/puppeteer/lib/Page.js:863:43)
    at Page.<anonymous> (/Users/roysabah/www/xx/server/node_modules/puppeteer/lib/helper.js:112:23)
    at Whatsapp.<anonymous> (/Users/roysabah/www/xx/server/node_modules/sulla/dist/api/layers/group.layer.js:161:60)
    at step (/Users/roysabah/www/xx/server/node_modules/sulla/dist/api/layers/group.layer.js:46:23)
    at Object.next (/Users/roysabah/www/xx/server/node_modules/sulla/dist/api/layers/group.layer.js:27:53)
    at /Users/roysabah/www/xx/server/node_modules/sulla/dist/api/layers/group.layer.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/roysabah/www/xx/server/node_modules/sulla/dist/api/layers/group.layer.js:17:12)
    at Whatsapp.GroupLayer.addParticipant (/Users/roysabah/www/xx/server/node_modules/sulla/dist/api/layers/group.layer.js:158:16)
  -- ASYNC --
    at Page.<anonymous> (/Users/roysabah/www/xx/server/node_modules/puppeteer/lib/helper.js:111:15)
    at Whatsapp.<anonymous> (/Users/roysabah/www/xx/server/node_modules/sulla/dist/api/layers/group.layer.js:161:60)
    at step (/Users/roysabah/www/xx/server/node_modules/sulla/dist/api/layers/group.layer.js:46:23)
    at Object.next (/Users/roysabah/www/xx/server/node_modules/sulla/dist/api/layers/group.layer.js:27:53)
    at /Users/roysabah/www/xx/server/node_modules/sulla/dist/api/layers/group.layer.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/roysabah/www/xx/server/node_modules/sulla/dist/api/layers/group.layer.js:17:12)
    at Whatsapp.GroupLayer.addParticipant (/Users/roysabah/www/xx/server/node_modules/sulla/dist/api/layers/group.layer.js:158:16)
    at start (/Users/roysabah/www/xx/server/whatsappWebApi2.js:66:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:72769) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:72769) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by JishantSingh** [comment]
Hi, n refers to the optional callback [done](https://github.com/danielcardeenas/sulla/blob/8704bc2ddc64895e71d1e4b7829182b3875f18a5/src/lib/wapi/functions/add-participant.js#L5). [This](https://github.com/danielcardeenas/sulla/blob/8704bc2ddc64895e71d1e4b7829182b3875f18a5/src/lib/wapi/functions/add-participant.js#L12) requires done to be a function.
