### ISSUE TITLE
a few hour later Target Closed error

### ISSUE THREAD

**Issue by ocracy** [danielcardeenas/sulla#298]
[24.04.2020 22:51.30.255] [ERROR] (node:41176) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at /Users/kerembekman/www/astro/node_modules/puppeteer/lib/Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/kerembekman/www/astro/node_modules/puppeteer/lib/Connection.js:182:12)
    at ExecutionContext._evaluateInternal (/Users/kerembekman/www/astro/node_modules/puppeteer/lib/ExecutionContext.js:107:44)
    at ExecutionContext.evaluate (/Users/kerembekman/www/astro/node_modules/puppeteer/lib/ExecutionContext.js:48:23)
    at ExecutionContext.<anonymous> (/Users/kerembekman/www/astro/node_modules/puppeteer/lib/helper.js:112:23)
    at DOMWorld.evaluate (/Users/kerembekman/www/astro/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/kerembekman/www/astro/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/Users/kerembekman/www/astro/node_modules/puppeteer/lib/Page.js:860:43)
    at Page.<anonymous> (/Users/kerembekman/www/astro/node_modules/puppeteer/lib/helper.js:112:23)
    at Whatsapp.<anonymous> (/Users/kerembekman/www/astro/node_modules/sulla/dist/api/layers/sender.layer.js:360:49)
    at step (/Users/kerembekman/www/astro/node_modules/sulla/dist/api/layers/sender.layer.js:46:23)
    at Object.next (/Users/kerembekman/www/astro/node_modules/sulla/dist/api/layers/sender.layer.js:27:53)
    at /Users/kerembekman/www/astro/node_modules/sulla/dist/api/layers/sender.layer.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/kerembekman/www/astro/node_modules/sulla/dist/api/layers/sender.layer.js:17:12)
    at Whatsapp.SenderLayer.startTyping (/Users/kerembekman/www/astro/node_modules/sulla/dist/api/layers/sender.layer.js:358:16)
  -- ASYNC --
    at Page.<anonymous> (/Users/kerembekman/www/astro/node_modules/puppeteer/lib/helper.js:111:15)
    at Whatsapp.<anonymous> (/Users/kerembekman/www/astro/node_modules/sulla/dist/api/layers/sender.layer.js:360:49)
    at step (/Users/kerembekman/www/astro/node_modules/sulla/dist/api/layers/sender.layer.js:46:23)
    at Object.next (/Users/kerembekman/www/astro/node_modules/sulla/dist/api/layers/sender.layer.js:27:53)
    at /Users/kerembekman/www/astro/node_modules/sulla/dist/api/layers/sender.layer.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/kerembekman/www/astro/node_modules/sulla/dist/api/layers/sender.layer.js:17:12)
    at Whatsapp.SenderLayer.startTyping (/Users/kerembekman/www/astro/node_modules/sulla/dist/api/layers/sender.layer.js:358:16)
    at Socket.<anonymous> (/Users/kerembekman/www/astro/whatsapp_bot/bot.js:154:27)
    at Socket.Emitter.emit (/Users/kerembekman/www/astro/node_modules/component-emitter/index.js:133:20)

**Comment by danielcardeenas** [comment]
This can be caused by several reasons. Most common is that your PC went sleeping mode or hibernate and the Chrome instance got shut down
