### ISSUE TITLE
when i send start and stop typing

### ISSUE THREAD

**Issue by DaniloTurini** [danielcardeenas/sulla#311]
- Checking for updates
- Authenticated
- Checking for updates
- Authenticated
- Injecting api...
- Checking for updates
- Authenticated
- Injecting api
(node:5792) UnhandledPromiseRejectionWarning: ReferenceError: start is not defined
    at e:\Sulla\index.js:10:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:5792) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5792) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by DaniloTurini** [comment]
problem solved. My stupidity
