### ISSUE TITLE
How can I build/test Sulla

### ISSUE THREAD

**Issue by sberlati** [danielcardeenas/sulla#47]
Hi!
I'm trying to contribute by adding features to the project (like sending messages to an ID, etc) but I can't find the way to test it. 

I forked the project, run ```npm install```, made the modifications, and then ```npm run-script build```, so the dist folder is generated.

I've also created a "testing" project where I use ```npm install [sulla_local_path]```. The problem is when I run the test project, I get:
```
UnhandledPromiseRejectionWarning: TypeError: puppeteer.launch is not a function
    at C:\nodeprojects\sulla\dist\controllers\browser.js:96:46
    at step (C:\nodeprojects\sulla\dist\controllers\browser.js:32:23)
    at Object.next (C:\nodeprojects\sulla\dist\controllers\browser.js:13:53)
    at C:\nodeprojects\sulla\dist\controllers\browser.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\nodeprojects\sulla\dist\controllers\browser.js:3:12)
    at initBrowser (C:\nodeprojects\sulla\dist\controllers\browser.js:92:12)
    at Object.<anonymous> (C:\nodeprojects\sulla\dist\controllers\browser.js:53:36)
    at step (C:\nodeprojects\sulla\dist\controllers\browser.js:32:23)
    at Object.next (C:\nodeprojects\sulla\dist\controllers\browser.js:13:53)
(node:10176) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10176) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I check in my testing project _node_modules_ folder and there is the puppeteer and sulla folder.

What steps am I missing?
Thanks for this project! And sorry for the bad english.

Greetings

**Comment by beeeku** [comment]
I guess this error will be fixed in this pull request https://github.com/danielcardeenas/sulla/pull/48

**Comment by sberlati** [comment]
That worked perfectly, thanks @beeeku !

**Comment by danielcardeenas** [comment]
Clone the repo

```sh
npm run build
npm run start
```
