### ISSUE TITLE
Error: Cannot find module 'sulla'

### ISSUE THREAD

**Issue by Theblood** [danielcardeenas/sulla#68]
Help Me Please :C not runnning 'sulla' :'(  my log 

`internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'sulla'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/theblood/Server_WH/start.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)`

**Comment by smashah** [comment]
Did you install it via npm? npm i sulla

**Comment by Theblood** [comment]
> Did you install it via npm? npm i sulla

yes, and I followed the steps of the start for the installation, but nothing works for me.

**Comment by Theblood** [comment]
@danielcardeenas @smashah  help me please 
 
 can you help me with the steps for a correct installation from this git

**Comment by MuallimCh** [comment]
> @danielcardeenas @smashah help me please
> 
> can you help me with the steps for a correct installation from this git

If you wish to install directly from this git

1. Go to directory where you extracted this git, and put all content to root directory
2. > npm install
3. > npm run build
4. On index.js put this requirement: var sulla = require("./dist/index.js");

**Comment by Theblood** [comment]
Thanks @MuallimCh  👍
