### ISSUE TITLE
Error: Evaluation failed: ReferenceError: webpackJsonp is not defined

### ISSUE THREAD

**Issue by bakwc** [danielcardeenas/sulla#689]
Hi! I'm trying to run an example (from README.md), and getting crash:

```
filipp@~/koding/test$ node mybot.js
Running mybot
✓ Checking for updates
✓ Authenticated
/Users/filipp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: ReferenceError: webpackJsonp is not defined
    at eval (eval at waitForPredicatePageFunction (:2:23), <anonymous>:5:25)
    at eval (eval at waitForPredicatePageFunction (:2:23), <anonymous>:6:23)
    at onRaf (__puppeteer_evaluation_script__:49:35)
    at pollRaf (__puppeteer_evaluation_script__:42:15)
    at waitForPredicatePageFunction (__puppeteer_evaluation_script__:7:22)
    at ExecutionContext._evaluateInternal (/Users/filipp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WaitTask.rerun (/Users/filipp/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:528:23)
```

**Comment by marlos7** [comment]
Looks like sulla has been discontinued, there's a good project I'm using!
https://github.com/jonalan7/Hydra-bot

**Comment by caickdias** [comment]
Hello! I solved that using `npm install puppeteer@latest`
