### ISSUE TITLE
Error: Failed to launch chrome!

### ISSUE THREAD

**Issue by AndikaTanpaH** [danielcardeenas/sulla#80]
```
⠋ Initializing whatsapp(node:18119) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/wabot/node_modules/puppeteer/.local-chromium/linux-674921/chrome-linux/chrome: 1: /wabot/node_modules/puppeteer/.local-chromium/linux-674921/chrome-linux/chrome: Syntax error: Unterminated quoted string


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/wabot/node_modules/puppeteer/lib/Launcher.js:349:14)
    at Interface.helper.addEventListener (/wabot/node_modules/puppeteer/lib/Launcher.js:338:50)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:368:8)
    at Socket.onend (readline.js:147:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
(node:18119) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18119) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Im use Ubuntu 16.04  32bit
node v8.16.1
npm 6.11.3

where I must fix it? It's not support 32bit?

**Comment by Mrjavaci** [comment]
Google ended Chrome&Chromium support for 32-bit linux at 2012.

**Comment by AndikaTanpaH** [comment]
@Mrjavaci no, chromium is still support for 32bit until now
but if using chrome, then is not working for my machine or 32bit linux.
thanks for this info

**Comment by robertsLando** [comment]
@danielcardeenas Is this related to https://github.com/danielcardeenas/sulla/issues/229?

**Comment by danielcardeenas** [comment]
If I understand correctly, it sounds like I need to add a flag to force it to use chromium then. Let me quick fix it

**Comment by danielcardeenas** [comment]
Should be fixed here: https://github.com/danielcardeenas/sulla/pull/232

Now you can specify `useChrome`  to force Chromium
```typescript
const client = await create('session', undefined, {
  useChrome: false,
});
```

If your environment does not support any of those, then you cannot use sulla
